plugins {
    id 'java'
}

group='org.rvschool'
version='1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // JUnit 5
    testImplementation 'org.junit.jupiter:junit-jupiter:6.0.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // RestAssured for API testing and API clients
    implementation 'io.rest-assured:rest-assured:6.0.0'

    // AssertJ Core
    testImplementation 'org.assertj:assertj-core:4.0.0-M1'

    // Allure
    testImplementation 'io.qameta.allure:allure-junit5:2.33.0'
    testImplementation 'io.qameta.allure:allure-rest-assured:2.33.0'

    // Jackson for JSON processing
    implementation 'tools.jackson.core:jackson-databind:3.1.2'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.21'
}

test {
    useJUnitPlatform()
}